Repository messerli-informatik-ag/utility, pull requests merged in 2019-03, with the labels that each got.

#1 Setup infrastructure
  .gitignore
  .nuspec
  .paket/Paket.Restore.targets
  .paket/paket.bootstrapper.exe
  .paket/paket.exe
  .paket/paket.runtimeconfig.json
  .paket/paket.targets
  .travis.yml
  Utility.Test/Utility.Test.csproj
  Utility.sln
  Utility/Utility.csproj
  license_apache.txt
  license_mit.txt
  paket.dependencies
  readme.md
Labels: enhancement

#2 Fix CI
  .gitignore
  .paket/paket.bootstrapper.exe
  .travis.yml
  readme.md
Labels: enhancement

#3 Optimize CI
  .travis.yml
Labels: enhancement

#4 Rename assemblies and namespaces in order to have a unique NuGet package ID
  .nuspec
  Utility.Test/EnumerableTest.cs
  Utility.Test/Extension/EnumerableExtensionTest.cs
  Utility.Test/Extension/FirstOrDefaultAsyncTest.cs
  Utility.Test/Extension/MathExtensionsTest.cs
  Utility.Test/Extension/WithIndexTest.cs
  Utility.Test/MathTest.cs
  Utility.Test/Utility.Test.csproj
  Utility/Enumerable.cs
  Utility/Extension/EnumerableExtension.cs
  Utility/Extension/FirstOrDefaultAsyncExtension.cs
  Utility/Extension/MathExtension.cs
  Utility/Extension/TypeExtension.cs
  Utility/Extension/WithIndexExtension.cs
  Utility/Math.cs
  Utility/Utility.csproj
  readme.md
Labels: enhancement

#5 Remove unused packages
  paket.dependencies
Labels: enhancement

#6 Add metadata files to solution
  Utility.sln
Labels: enhancement

#7 Fix type checks
  Utility.Test/Extension/TypeExtensionTest.cs
  Utility/Extension/TypeExtension.cs
  changelog.md
Labels: bug

#8 Release 0.1.1
  .nuspec
  Utility.sln
  Utility/Utility.csproj
  changelog.md
Labels: release
